console.log(typeof 42);             // 'number'
console.log(typeof true);           // 'boolean'
console.log(typeof 'hello');        // 'string'
console.log(typeof function(){});   // 'function'
console.log(typeof {name: 'mark'}); // 'object'
